#!/usr/bin/env python3
"""Profile strategy selection for Xray-Cooperative-Overlay.

This module is intentionally a control-plane selector. It does not emit live TLS,
does not manipulate packets, and does not change trust stores. It maps observed
failure labels and operator intent to named Xray profiles that are already present
or generated by config-src.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable


@dataclass(frozen=True)
class ProfileCandidate:
    profile_id: str
    profile_path: str
    intent: str
    tags: tuple[str, ...] = ()
    priority: int = 100
    requires_confirmation: bool = False


@dataclass(frozen=True)
class StrategyInput:
    failure_labels: tuple[str, ...]
    operator_intent: str = "balanced"
    session_counter: int = 0
    avoid_profiles: tuple[str, ...] = ()


@dataclass(frozen=True)
class StrategyDecision:
    selected_profile_id: str
    selected_profile_path: str
    reason: str
    confidence: str
    confirmation_required: bool = False
    evidence: dict[str, object] = field(default_factory=dict)


def pool_index(session_counter: int, pool_size: int) -> int:
    """Return O(1) deterministic index into a power-of-two profile/template pool."""
    if pool_size < 1:
        raise ValueError("pool_size must be >= 1")
    if pool_size & (pool_size - 1):
        raise ValueError("pool_size must be a power of two for bitmask selection")
    if session_counter < 0:
        raise ValueError("session_counter must be >= 0")
    return session_counter & (pool_size - 1)


def choose_profile(candidates: Iterable[ProfileCandidate], request: StrategyInput) -> StrategyDecision:
    pool = [candidate for candidate in candidates if candidate.profile_id not in set(request.avoid_profiles)]
    if not pool:
        raise ValueError("no profile candidates available after avoid_profiles filtering")

    labels = {label.strip().lower() for label in request.failure_labels if label.strip()}
    intent = request.operator_intent.strip().lower() or "balanced"

    def score(candidate: ProfileCandidate) -> tuple[int, int, str]:
        tags = {tag.lower() for tag in candidate.tags}
        value = 0
        reasons: list[str] = []
        if candidate.intent.lower() == intent:
            value += 30
            reasons.append(f"intent:{intent}")
        if "dns_leak" in labels and "fakedns" in tags:
            value += 20
            reasons.append("dns_leak->fakedns")
        if "webrtc_leak" in labels and "tun" in tags:
            value += 20
            reasons.append("webrtc_leak->tun")
        if "static_ja3" in labels and "multi_utls" in tags:
            value += 15
            reasons.append("static_ja3->multi_utls")
        if "tls_block" in labels and "fragment" in tags:
            value += 15
            reasons.append("tls_block->fragment")
        if "trust_ioc" in labels and "profile_trust" in tags:
            value += 10
            reasons.append("trust_ioc->profile_trust")
        return value, -candidate.priority, ",".join(reasons) or "default"

    ranked = sorted(pool, key=score, reverse=True)
    selected = ranked[pool_index(request.session_counter, _nearest_power_of_two(len(ranked))) % len(ranked)]
    selected_score = score(selected)
    return StrategyDecision(
        selected_profile_id=selected.profile_id,
        selected_profile_path=selected.profile_path,
        reason=selected_score[2],
        confidence="medium" if selected_score[0] > 0 else "low",
        confirmation_required=selected.requires_confirmation,
        evidence={
            "failure_labels": sorted(labels),
            "operator_intent": intent,
            "ranked_profiles": [candidate.profile_id for candidate in ranked],
        },
    )


def _nearest_power_of_two(value: int) -> int:
    power = 1
    while power < value:
        power <<= 1
    return power
